### ISSUE TITLE
Stack elements on your homepage using flexbox (and media queries) so that it looks even better on mobile

### ISSUE THREAD

**Issue by bedrock-adam** [reemawad3/reemawad3.github.io#3]
See how [this website](https://thecodercoder.github.io/responsive-layout-flexbox/) responds to resizing the window. Tutorial [here](https://coder-coder.com/build-flexbox-website-layout/).

Challenge to push the limits of your CSS knowledge. Don't be hard on yourself if things don't make sense! Give yourself plenty of time. Please don't feel like you need to do this prior to booking another call!

**Comment by bedrock-adam** [comment]
1. `git checkout -b layout/mobile_stack` (to create a local branch)
2. make your changes in that branch and `git commit`
3. `git push -u origin layout/mobile_stack` (to push the local branch up to remote e.g. github)
4. Open a Pull Request in github, based on the `layout/mobile_stack` branch
5. Attach the pull request to this issue
6. Request me as a reviewer on the pull request and can give feedback (or a +1)

**Comment by bedrock-adam** [comment]
Mobile first

![Screenshot from 2020-12-04 11-08-16](https://user-images.githubusercontent.com/394074/101105233-20614b80-3621-11eb-9e49-a8f6de9d310e.png)

Desktop

![Screenshot from 2020-12-04 11-08-26](https://user-images.githubusercontent.com/394074/101105223-1c352e00-3621-11eb-8521-8842c108d3fb.png)

**Comment by Bijoy-007** [comment]
I can do this even better using bootstrap grid

or flexbox if you don't wanna use bootstrap .

**Comment by Bijoy-007** [comment]
Assign me
