### ISSUE TITLE
Make layout consistent across all pages

### ISSUE THREAD

**Issue by bedrock-adam** [reemawad3/reemawad3.github.io#4]

**Comment by bedrock-adam** [comment]
For this one @reemawad3, would you like me to review the changes via a pull request?

Thinking it'll give you some great experience in how things would run in a company if you're interested?

1. `git checkout -b layout/make_consistent` (to create a local branch)
2. make your changes in that branch and `git commit`
3. `git push -u origin layout/make_consistent` (to push the local branch up to remote e.g. github)
4. Open a Pull Request in github, based on the `layout/make_consistent` branch
5. Link this issue to the pull request
6. Request me as a reviewer on the pull request and can give feedback (or a :+1:)

**Comment by reemawad3** [comment]
hello Adam
thank you very much
ok i will try and will see what will happen
have a great day

**Comment by reemawad3** [comment]
![Capture](https://user-images.githubusercontent.com/73262473/99013227-25902500-25a4-11eb-88c8-f07301c41013.PNG)
![Capture2](https://user-images.githubusercontent.com/73262473/99013229-26c15200-25a4-11eb-8b7d-bd58cf3105f3.PNG)
 i can't commit it

**Comment by reemawad3** [comment]
i think that's happened because i did the changes before doing the branch :)

**Comment by bedrock-adam** [comment]
Looks like you just need to remove the `<>` e.g. try `git add education.html`

**Comment by bedrock-adam** [comment]
Great work on this one Reem!
